language: python
python:
  - "2.7"

install:
    - python setup.py install
    - pip install django
    - pip install django-tastypie

services:
    - mongodb

script:
    - ./runtests

env:
    - DJANGO_SETTINGS_MODULE='tests.settings'